<?php
/**
 * Created by PhpStorm.
 * User: compiler
 * Date: 18-3-25
 * Time: 下午8:10
 */

namespace app\api\service;

use app\api\model\OrderModel;
use app\api\model\ProductModel;
use app\api\service\Order as OrderService;
use app\lib\enum\OrderStatusEnum;
use think\Db;
use think\Exception;
use think\facade\Log;

require __DIR__ . '/../../../extend/WxPay/WxPay.Api.php';  //__DIR__ 是指本文件Pay.php 所在的目录
//WxPayNotify 类是在WxNotify.php 中的，但require  WxPay.Api.php ，因为WxPay.Api.php中包括WxNotify.php

class WxNotify extends \WxPayNotify
{
    public function NotifyProcess($data, &$msg)
    {
//        <xml>
//  <appid><![CDATA[wx2421b1c4370ec43b]]></appid>
//  <attach><![CDATA[支付测试]]></attach>
//  <bank_type><![CDATA[CFT]]></bank_type>
//  <fee_type><![CDATA[CNY]]></fee_type>
//  <is_subscribe><![CDATA[Y]]></is_subscribe>
//  <mch_id><![CDATA[10000100]]></mch_id>
//  <nonce_str><![CDATA[5d2b6c2a8db53831f7eda20af46e531c]]></nonce_str>
//  <openid><![CDATA[oUpF8uMEb4qRXf22hE3X68TekukE]]></openid>
//  <out_trade_no><![CDATA[1409811653]]></out_trade_no>
//  <result_code><![CDATA[SUCCESS]]></result_code>
//  <return_code><![CDATA[SUCCESS]]></return_code>
//  <sign><![CDATA[B552ED6B279343CB493C5DD0D78AB241]]></sign>
//  <sub_mch_id><![CDATA[10000100]]></sub_mch_id>
//  <time_end><![CDATA[20140903131540]]></time_end>
//  <total_fee>1</total_fee>
//<coupon_fee><![CDATA[10]]></coupon_fee>
//<coupon_count><![CDATA[1]]></coupon_count>
//<coupon_type><![CDATA[CASH]]></coupon_type>
//<coupon_id><![CDATA[10000]]></coupon_id>
//<coupon_fee><![CDATA[100]]></coupon_fee>
//  <trade_type><![CDATA[JSAPI]]></trade_type>
//  <transaction_id><![CDATA[1004400740201409030005092168]]></transaction_id>
//</xml>
        //return parent::NotifyProcess($data, $msg); // TODO: Change the autogenerated stub

        if ($data['result_code' =='SUCCESS']){ //$data 已被转成数组，见NotifyProcess 方法的参数说明

            $orderNo = $data['out_trade_no'];
            Db::startTrans();
            try{
                $order = OrderModel::where('order_no','=',$orderNo)->find();

                if ($order->status ==1){
                    $service = new OrderService();
                    $stockStatus = $service->checkOrderStock($order->id);
                    if ($stockStatus['pass']){
                        $this->updateOrderStatus($order->id,true);
                        $this->reduceStock($stockStatus);
                    }else{
                        $this->updateOrderStatus($order->id,false);
                    }
                }
                Db::commit();
                return true; //见父方法 NotifyProcess 说明。
            }catch (Exception $ex){
                Db::rollback();
                Log::record($ex);
                return false;
            }
        }else{
            return false;
        }


    }

    private function reduceStock($stockStatus){
        foreach ($stockStatus['pStatusArray'] as $singlePStatus){
            ProductModel::where('id','=',$singlePStatus['id'])
                ->setDec('stock',$stockStatus['count']); //setDec 可以对某个field 做减法

        }
    }

    private function updateOrderStatus($orderID,$success){
        $status = $success?
            OrderStatusEnum::PAID :
            OrderStatusEnum::PAID_BUT_OUT_OF;
        OrderModel::where('id','=',$orderID)->update(['status'=>$status]);
    }

}